"""The ambient-scene verbs: the model can ask for one of a closed set of scenes,
the TV reports which is showing, and the contract the TV app compiles against
carries both."""
import json
from pathlib import Path

import pytest
from conftest import PERSONA
from pydantic import ValidationError

from tv_avatar.agent.commands import (
    AWAITS_RESULT,
    HideAmbient,
    ShowAmbient,
    Verb,
    parse_command,
)
from tv_avatar.agent.envelope import TurnPlan, describe_capabilities, plan_violations
from tv_avatar.agent.prompt import build_system_prompt
from tv_avatar.ambient.scenes import SCENES, describe_scenes
from tv_avatar.control.protocol import (
    PROTOCOL_VERSION,
    Playback,
    ScreenState,
    parse_client_message,
)
from tv_avatar.session.state import SessionStore

CONTRACTS = Path(__file__).resolve().parents[1] / "contracts"


def test_show_ambient_takes_only_a_known_scene():
    for scene in SCENES:
        cmd = parse_command("show_ambient", {"scene": scene.id})
        assert isinstance(cmd, ShowAmbient) and cmd.scene == scene.id
    with pytest.raises(ValueError):
        parse_command("show_ambient", {"scene": "volcano"})
    with pytest.raises(ValueError):
        parse_command("show_ambient", {})


def test_hide_ambient_takes_no_arguments():
    assert isinstance(parse_command("hide_ambient", {}), HideAmbient)


def test_ambient_verbs_never_block_the_turn():
    # Making the video takes about a minute; the avatar must keep talking meanwhile.
    assert Verb.SHOW_AMBIENT not in AWAITS_RESULT and Verb.HIDE_AMBIENT not in AWAITS_RESULT


def test_turn_plan_can_carry_an_ambient_action():
    request = {"operation": "control", "title": None, "title_id": None}
    plan = TurnPlan.model_validate({
        "intent": "control", "request": request, "say": "Here's the fireplace.",
        "actions": [{"verb": "show_ambient", "scene": "fireplace"}]})
    assert plan.actions[0].scene == "fireplace"
    # Ambient is not title-directed, so no operation licenses or forbids it.
    assert not plan_violations(plan)
    with pytest.raises(ValidationError):
        TurnPlan.model_validate({"intent": "control", "request": request, "say": "",
                                 "actions": [{"verb": "show_ambient", "scene": "lava lamp"}]})


def test_manifest_and_rules_tell_the_model_about_every_scene():
    manifest = describe_capabilities()
    assert "- show_ambient" in manifest and "- hide_ambient" in manifest
    for scene in SCENES:
        assert scene.id in manifest
    assert describe_scenes() in manifest
    rules = build_system_prompt(PERSONA.language)
    assert "`show_ambient`" in rules and "`hide_ambient`" in rules


def _screen(**over) -> ScreenState:
    return ScreenState(view="grid", playback=Playback(state="stopped"), **over)


def test_screen_state_names_the_ambient_scene_on_its_own_line():
    s = SessionStore().create(60, PERSONA)
    s.update_screen(_screen(ambient="fireplace"))
    rendered = s.render_for_prompt()
    assert "Ambient scene: fireplace" in rendered
    assert "Playback: stopped" in rendered  # the scene is not playback: those rules stay off
    s.update_screen(_screen())
    assert "Ambient" not in s.render_for_prompt()


def test_a_tv_app_without_the_field_still_reports_its_screen():
    raw = json.dumps({"v": PROTOCOL_VERSION, "type": "screen_state", "state": {
        "view": "grid", "playback": {"state": "stopped"}}})
    assert parse_client_message(raw).state.ambient is None


def test_committed_contracts_carry_the_ambient_vocabulary():
    # Generated by tools/export_schemas.py; this fails when a verb lands without a rerun.
    ts = (CONTRACTS / "protocol.d.ts").read_text(encoding="utf-8")
    assert '"show_ambient"' in ts and '"hide_ambient"' in ts
    assert "export interface ShowAmbientArgs {\n  scene: " in ts
    assert "ambient?: string | null;" in ts
    schema = json.loads((CONTRACTS / "protocol.schema.json").read_text(encoding="utf-8"))
    assert set(schema["commands"]["show_ambient"]["properties"]["scene"]["enum"]) == {s.id for s in SCENES}
