// GENERATED by tools/export_schemas.py — do not edit by hand.
// Regenerate with: uv run python tools/export_schemas.py

export const PROTOCOL_VERSION = 1;

export type Verb = "back" | "close" | "focus" | "home" | "navigate" | "open_details" | "pause" | "play" | "resume" | "search_catalog" | "seek" | "show_products";

/** Verbs whose handler awaits a `result` message from the TV app. */
export type AwaitsResult = "search_catalog";

export interface Tile { title_id: string; name: string; position: number; }

export interface Playback {
  state: "stopped" | "playing" | "paused";
  title_id: string | null;
  position_s: number;
}

export interface ScreenState {
  view: "grid" | "details" | "player" | "products";
  rail_id: string | null;
  focus_index: number | null;
  tiles: Tile[];
  playback: Playback;
}

export interface CommandMsg {
  v: typeof PROTOCOL_VERSION;
  type: "command";
  id: string;
  turn_id: string;
  verb: Verb;
  args: Record<string, unknown>;
  ts: number;
}

export interface AgentStatusMsg {
  v: typeof PROTOCOL_VERSION;
  type: "agent_status";
  state: "idle" | "listening" | "thinking" | "speaking";
}

export interface TranscriptMsg {
  v: typeof PROTOCOL_VERSION;
  type: "transcript";
  role: "user" | "assistant";
  text: string;
  final: boolean;
}

export interface ErrorMsg {
  v: typeof PROTOCOL_VERSION;
  type: "error";
  code: string;
  message: string;
}

export type ServerMessage = CommandMsg | AgentStatusMsg | TranscriptMsg | ErrorMsg;
