// GENERATED by tools/export_schemas.py — do not edit by hand.
// Regenerate with: uv run python tools/export_schemas.py

export const PROTOCOL_VERSION = 1;

export type Verb = "back" | "close" | "focus" | "hide_ambient" | "home" | "navigate" | "open_details" | "pause" | "play" | "resume" | "search_catalog" | "seek" | "show_ambient" | "show_products" | "show_titles";

/** Verbs whose handler awaits a `result` message from the TV app. */
export type AwaitsResult = "search_catalog";

// ---- command arguments, one interface per verb ----
export interface BackArgs {}

export interface CloseArgs {}

export interface FocusArgs {
  title_id: string;
}

export interface HideAmbientArgs {}

export interface HomeArgs {}

export interface NavigateArgs {
  direction: "up" | "down" | "left" | "right";
  count?: number;
}

export interface OpenDetailsArgs {
  title_id: string;
}

export interface PauseArgs {}

export interface PlayArgs {
  title_id: string;
  resume_from?: number | null;
}

export interface ResumeArgs {}

export interface SearchCatalogArgs {
  query: string;
  limit?: number;
}

export interface SeekArgs {
  to_seconds?: number | null;
  delta_seconds?: number | null;
}

export interface ShowAmbientArgs {
  scene: "garden" | "beach" | "fireplace";
}

export interface ShowProductsArgs {
  title_id: string;
  scene_at?: number | null;
}

export interface ShowTitlesArgs {
  title_ids: Array<string>;
  label?: string;
}

export interface CommandArgsByVerb {
  "back": BackArgs;
  "close": CloseArgs;
  "focus": FocusArgs;
  "hide_ambient": HideAmbientArgs;
  "home": HomeArgs;
  "navigate": NavigateArgs;
  "open_details": OpenDetailsArgs;
  "pause": PauseArgs;
  "play": PlayArgs;
  "resume": ResumeArgs;
  "search_catalog": SearchCatalogArgs;
  "seek": SeekArgs;
  "show_ambient": ShowAmbientArgs;
  "show_products": ShowProductsArgs;
  "show_titles": ShowTitlesArgs;
}

// ---- client -> server ----
export interface AckMsg {
  v: 1;
  type: "ack";
  command_id: string;
  ok: boolean;
  error?: string | null;
}

export interface Playback {
  state: "stopped" | "playing" | "paused";
  title_id?: string | null;
  position_s?: number;
}

export interface ResultMsg {
  v: 1;
  type: "result";
  command_id: string;
  data: Record<string, unknown>;
}

export interface ScreenState {
  view: "grid" | "details" | "player" | "products";
  rail_id?: string | null;
  focus_index?: number | null;
  tiles?: Array<Tile>;
  playback: Playback;
  ambient?: string | null;
}

export interface ScreenStateMsg {
  v: 1;
  type: "screen_state";
  state: ScreenState;
}

export interface Tile {
  title_id: string;
  name: string;
  position: number;
  shoppable?: boolean;
}

export interface UserEventMsg {
  v: 1;
  type: "user_event";
  event: string;
  detail?: Record<string, unknown>;
}

export type ClientMessage = ScreenStateMsg | AckMsg | ResultMsg | UserEventMsg;

// ---- server -> client ----
export interface AgentStatusMsg {
  v: 1;
  type: "agent_status";
  state: "idle" | "listening" | "thinking" | "speaking";
}

export interface CommandMsgBase {
  v: 1;
  type: "command";
  id: string;
  turn_id: string;
  ts: number;
}

/** Discriminated on `verb`; `args` is typed per verb. */
export type CommandMsg = {
  [V in Verb]: CommandMsgBase & { verb: V; args: CommandArgsByVerb[V] };
}[Verb];

export interface ErrorMsg {
  v: 1;
  type: "error";
  code: string;
  message: string;
}

export interface TranscriptMsg {
  v: 1;
  type: "transcript";
  role: "user" | "assistant";
  text: string;
  final: boolean;
}

export type ServerMessage = CommandMsg | AgentStatusMsg | TranscriptMsg | ErrorMsg;
