"""Generate the contract artifacts the TV repository consumes.

Run: uv run python tools/export_schemas.py
The TV app cannot compile a command this backend would reject, because
both sides derive from agent/commands.py.
"""
import json
from pathlib import Path

from pydantic import TypeAdapter

from tv_avatar.agent.commands import AWAITS_RESULT, COMMAND_MODELS
from tv_avatar.control.protocol import (
    PROTOCOL_VERSION,
    ClientMessage,
    ServerMessage,
)

OUT_DIR = Path(__file__).resolve().parents[1] / "contracts"


def build_schema_bundle() -> dict:
    return {
        "protocol_version": PROTOCOL_VERSION,
        "awaits_result": sorted(v.value for v in AWAITS_RESULT),
        "commands": {
            verb.value: model.model_json_schema()
            for verb, model in COMMAND_MODELS.items()
        },
        "client_messages": TypeAdapter(ClientMessage).json_schema(),
        "server_messages": TypeAdapter(ServerMessage).json_schema(),
    }


def _ts_type(schema: dict) -> str:
    """Map the JSON Schema subset Pydantic emits for our models to TypeScript."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " | ".join(_ts_type(s) for s in schema[key])
    match schema.get("type"):
        case "string":
            return "string"
        case "number" | "integer":
            return "number"
        case "boolean":
            return "boolean"
        case "null":
            return "null"
        case "array":
            return f"Array<{_ts_type(schema.get('items', {}))}>"
        case "object":
            if "properties" in schema:
                return "{ " + " ".join(_ts_fields(schema)) + " }"
            return "Record<string, unknown>"
    return "unknown"


def _ts_fields(
    schema: dict, *, omit: frozenset[str] = frozenset(), all_required: bool = False
) -> list[str]:
    required = set(schema.get("required", []))
    lines = []
    for name, prop in schema.get("properties", {}).items():
        if name in omit:
            continue
        # A const field (v, type, verb) is always present on the wire even
        # though Pydantic marks it optional because it has a default.
        # Server-emitted messages serialise every field, so `all_required`
        # is set for the server -> client direction.
        opt = "" if all_required or name in required or "const" in prop else "?"
        lines.append(f"{name}{opt}: {_ts_type(prop)};")
    return lines


def _ts_interface(
    name: str,
    schema: dict,
    *,
    omit: frozenset[str] = frozenset(),
    all_required: bool = False,
) -> str:
    fields = _ts_fields(schema, omit=omit, all_required=all_required)
    if not fields:
        return f"export interface {name} {{}}"
    body = "\n".join(f"  {line}" for line in fields)
    return f"export interface {name} {{\n{body}\n}}"


def _union_members(schema: dict) -> list[str]:
    return [_ts_type(s) for s in schema.get("oneOf", schema.get("anyOf", []))]


def render_typescript(bundle: dict) -> str:
    verbs = sorted(bundle["commands"])
    client, server = bundle["client_messages"], bundle["server_messages"]

    out = [
        "// GENERATED by tools/export_schemas.py — do not edit by hand.",
        "// Regenerate with: uv run python tools/export_schemas.py",
        "",
        f"export const PROTOCOL_VERSION = {bundle['protocol_version']};",
        "",
        "export type Verb = " + " | ".join(json.dumps(v) for v in verbs) + ";",
        "",
        "/** Verbs whose handler awaits a `result` message from the TV app. */",
        "export type AwaitsResult = "
        + " | ".join(json.dumps(v) for v in bundle["awaits_result"]) + ";",
        "",
        "// ---- command arguments, one interface per verb ----",
    ]

    args_names: dict[str, str] = {}
    for verb in verbs:
        schema = bundle["commands"][verb]
        name = f"{schema['title']}Args"
        args_names[verb] = name
        out += [_ts_interface(name, schema, omit=frozenset({"verb"})), ""]

    out += [
        "export interface CommandArgsByVerb {",
        *[f"  {json.dumps(v)}: {args_names[v]};" for v in verbs],
        "}",
        "",
        "// ---- client -> server ----",
    ]
    for name, schema in sorted(client["$defs"].items()):
        out += [_ts_interface(name, schema), ""]
    out += [
        "export type ClientMessage = " + " | ".join(_union_members(client)) + ";",
        "",
        "// ---- server -> client ----",
    ]
    for name, schema in sorted(server["$defs"].items()):
        if name == "CommandMsg":
            out += [
                _ts_interface(
                    "CommandMsgBase",
                    schema,
                    omit=frozenset({"verb", "args"}),
                    all_required=True,
                ),
                "",
            ]
            out += [
                "/** Discriminated on `verb`; `args` is typed per verb. */",
                "export type CommandMsg = {",
                "  [V in Verb]: CommandMsgBase & { verb: V; args: CommandArgsByVerb[V] };",
                "}[Verb];",
                "",
            ]
        else:
            out += [_ts_interface(name, schema, all_required=True), ""]
    out += ["export type ServerMessage = " + " | ".join(_union_members(server)) + ";", ""]
    return "\n".join(out)


def main() -> None:
    bundle = build_schema_bundle()
    OUT_DIR.mkdir(exist_ok=True)
    # Explicit encoding: write_text() defaults to the platform codec, and on Windows
    # that is cp1252 — the em-dash in the .d.ts header came out as a lone 0x97 byte,
    # which is not UTF-8 and made the contract unreadable on Linux (PR #15).
    (OUT_DIR / "protocol.schema.json").write_text(
        json.dumps(bundle, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (OUT_DIR / "protocol.d.ts").write_text(render_typescript(bundle), encoding="utf-8")
    print(f"wrote {OUT_DIR}/protocol.schema.json and protocol.d.ts")


if __name__ == "__main__":
    main()
