"""Generate the contract artifacts the TV repository consumes.

Run: uv run python tools/export_schemas.py
The TV app cannot compile a command this backend would reject, because
both sides derive from agent/commands.py.
"""
import json
from pathlib import Path

from pydantic import TypeAdapter

from tv_avatar.agent.commands import COMMAND_MODELS, AWAITS_RESULT, Verb
from tv_avatar.control.protocol import (
    PROTOCOL_VERSION,
    ClientMessage,
    ServerMessage,
)

OUT_DIR = Path(__file__).resolve().parents[1] / "contracts"


def build_schema_bundle() -> dict:
    return {
        "protocol_version": PROTOCOL_VERSION,
        "awaits_result": sorted(v.value for v in AWAITS_RESULT),
        "commands": {
            verb.value: model.model_json_schema()
            for verb, model in COMMAND_MODELS.items()
        },
        "client_messages": TypeAdapter(ClientMessage).json_schema(),
        "server_messages": TypeAdapter(ServerMessage).json_schema(),
    }


def render_typescript(bundle: dict) -> str:
    verbs = " | ".join(f'"{v}"' for v in sorted(bundle["commands"]))
    awaits = " | ".join(f'"{v}"' for v in bundle["awaits_result"])
    return f"""// GENERATED by tools/export_schemas.py — do not edit by hand.
// Regenerate with: uv run python tools/export_schemas.py

export const PROTOCOL_VERSION = {bundle["protocol_version"]};

export type Verb = {verbs};

/** Verbs whose handler awaits a `result` message from the TV app. */
export type AwaitsResult = {awaits};

export interface Tile {{ title_id: string; name: string; position: number; }}

export interface Playback {{
  state: "stopped" | "playing" | "paused";
  title_id: string | null;
  position_s: number;
}}

export interface ScreenState {{
  view: "grid" | "details" | "player" | "products";
  rail_id: string | null;
  focus_index: number | null;
  tiles: Tile[];
  playback: Playback;
}}

export interface CommandMsg {{
  v: typeof PROTOCOL_VERSION;
  type: "command";
  id: string;
  turn_id: string;
  verb: Verb;
  args: Record<string, unknown>;
  ts: number;
}}

export interface AgentStatusMsg {{
  v: typeof PROTOCOL_VERSION;
  type: "agent_status";
  state: "idle" | "listening" | "thinking" | "speaking";
}}

export interface TranscriptMsg {{
  v: typeof PROTOCOL_VERSION;
  type: "transcript";
  role: "user" | "assistant";
  text: string;
  final: boolean;
}}

export interface ErrorMsg {{
  v: typeof PROTOCOL_VERSION;
  type: "error";
  code: string;
  message: string;
}}

export type ServerMessage = CommandMsg | AgentStatusMsg | TranscriptMsg | ErrorMsg;
"""


def main() -> None:
    bundle = build_schema_bundle()
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "protocol.schema.json").write_text(
        json.dumps(bundle, indent=2, sort_keys=True) + "\n"
    )
    (OUT_DIR / "protocol.d.ts").write_text(render_typescript(bundle))
    print(f"wrote {OUT_DIR}/protocol.schema.json and protocol.d.ts")


if __name__ == "__main__":
    main()
